name: chatapp
services:

  web:
      build: .
      command: >
        sh -c "
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 a_core.asgi:application
        "
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        - db
        - redis

  db:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
        - ./postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: